### ISSUE TITLE
[2018] Duplas

### ISSUE THREAD

**Issue by jemaf** [COLTEC-DAW/Prova-jQuery-JavaScript#19]
Apresente os integrantes da dupla junto do tema do seu bracket!!

### Exemplo

**Grupo 01**

* Maria Bonita
* Lampião

*Tema: Comédias brasileiras.*

**Comment by BernardoGN** [comment]
**Grupo 01**

- Bernardo Nunes
- Willian Vítor

_Tema: Ranking de beleza da info_

**Comment by kingnowdo** [comment]
**Grupo 02**

- Reinaldo
- Guilherme

_Tema: Jogos com melhores roteiros_

**Comment by gegen07** [comment]
__Grupo 03__

- Bryan Santos
- Germano Barcelos

_Tema: Melhores Jogos de Futebol_

**Comment by MariSantos17** [comment]
**Grupo 04**

[ ] - João Gabriel 
[ ] - Mariana

_Tema: Séries da Netflix_

**Comment by RitaRez** [comment]
**Grupo 05**

- Rita
- Henrique

_Tema: Melhores "modões"_

**Comment by Veazey** [comment]
**Grupo 06**

- Gabriel
- Mateus

_Tema: Studio Ghibli vs Disney_

**Comment by mtgo007** [comment]
Grupo 08

- Mathias

- Dener
_Tema: Quem jogou mais na copa de 1958?_

**Comment by mtgo007** [comment]
Grupo 08 - Bracket
https://mtgo007.github.io/index.html

**Comment by dellareti** [comment]
**Grupo 09**

- Ítalo Dell  Areti 
- Artur Parreiras
 
_Tema: Melhores vídeo games de todos os tempos_

**Comment by joaovitorbraga** [comment]
Grupo 10

- Caio 

- João Vitor

Tema: Super Heróis
